; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32-s3-main

[env_base]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
board_build.mcu = esp32s3
board_build.flash_size = 4MB
board_build.psram = enabled
board_build.partitions = default.csv
board_upload.flash_size = 4MB
build_unflags = -std=gnu++11
build_flags = 
	-std=gnu++17
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
upload_speed = 921600
monitor_speed = 115200
monitor_filters = send_on_enter
monitor_eol = CRLF

[env:esp32-s3-main]
extends = env_base
build_src_filter = 
	+<app/>
	+<common/calib/>
	+<common/sensors/>
	+<common/drivers/>
	+<common/eeprom/>
lib_deps = 
	adafruit/Adafruit GFX Library@^1.12.2
	adafruit/Adafruit SSD1306@^2.5.15
	constiko/RTC RV-3028-C7 Arduino Library@^2.1.0
	sensirion/Sensirion I2C SCD4x@^1.1.0

[env:esp32-s3-writer]
extends = env_base
build_src_filter =
	+<writer/>
	+<common/calib/>
	+<common/drivers/>
	+<common/eeprom/>
build_flags = 
	${env_base.build_flags}
	-DWRITER_MODE
lib_deps = sensirion/Sensirion I2C SCD4x@^1.1.0
